cfg:
  train_ds:
    manifest_filepath: datas/train.json
    sample_rate: 16000
    labels:
    - spk_0
    - spk_1
    - spk_10
    - spk_100
    - spk_101
    - spk_102
    - spk_103
    - spk_104
    - spk_105
    - spk_106
    - spk_107
    - spk_108
    - spk_109
    - spk_11
    - spk_110
    - spk_111
    - spk_112
    - spk_113
    - spk_114
    - spk_115
    - spk_116
    - spk_117
    - spk_118
    - spk_119
    - spk_12
    - spk_120
    - spk_121
    - spk_122
    - spk_123
    - spk_124
    - spk_125
    - spk_126
    - spk_127
    - spk_128
    - spk_129
    - spk_13
    - spk_130
    - spk_131
    - spk_132
    - spk_133
    - spk_134
    - spk_135
    - spk_136
    - spk_137
    - spk_138
    - spk_139
    - spk_14
    - spk_140
    - spk_141
    - spk_142
    - spk_143
    - spk_144
    - spk_145
    - spk_146
    - spk_147
    - spk_148
    - spk_149
    - spk_15
    - spk_150
    - spk_151
    - spk_152
    - spk_153
    - spk_154
    - spk_155
    - spk_156
    - spk_157
    - spk_158
    - spk_159
    - spk_16
    - spk_160
    - spk_161
    - spk_162
    - spk_163
    - spk_164
    - spk_165
    - spk_166
    - spk_167
    - spk_168
    - spk_169
    - spk_17
    - spk_170
    - spk_171
    - spk_172
    - spk_173
    - spk_174
    - spk_175
    - spk_176
    - spk_177
    - spk_178
    - spk_179
    - spk_18
    - spk_180
    - spk_181
    - spk_182
    - spk_183
    - spk_184
    - spk_185
    - spk_186
    - spk_187
    - spk_188
    - spk_189
    - spk_19
    - spk_190
    - spk_191
    - spk_192
    - spk_193
    - spk_194
    - spk_195
    - spk_196
    - spk_197
    - spk_198
    - spk_199
    - spk_2
    - spk_20
    - spk_200
    - spk_201
    - spk_202
    - spk_203
    - spk_204
    - spk_205
    - spk_206
    - spk_207
    - spk_208
    - spk_209
    - spk_21
    - spk_210
    - spk_211
    - spk_212
    - spk_213
    - spk_214
    - spk_215
    - spk_216
    - spk_217
    - spk_218
    - spk_219
    - spk_22
    - spk_220
    - spk_221
    - spk_222
    - spk_223
    - spk_224
    - spk_225
    - spk_226
    - spk_227
    - spk_228
    - spk_229
    - spk_23
    - spk_230
    - spk_231
    - spk_232
    - spk_233
    - spk_234
    - spk_235
    - spk_236
    - spk_237
    - spk_238
    - spk_239
    - spk_24
    - spk_240
    - spk_241
    - spk_242
    - spk_243
    - spk_244
    - spk_245
    - spk_246
    - spk_247
    - spk_248
    - spk_249
    - spk_25
    - spk_250
    - spk_251
    - spk_252
    - spk_253
    - spk_254
    - spk_255
    - spk_256
    - spk_257
    - spk_258
    - spk_259
    - spk_26
    - spk_260
    - spk_261
    - spk_262
    - spk_263
    - spk_264
    - spk_265
    - spk_266
    - spk_267
    - spk_268
    - spk_269
    - spk_27
    - spk_270
    - spk_271
    - spk_272
    - spk_273
    - spk_274
    - spk_275
    - spk_276
    - spk_277
    - spk_278
    - spk_279
    - spk_28
    - spk_280
    - spk_281
    - spk_282
    - spk_283
    - spk_284
    - spk_285
    - spk_286
    - spk_287
    - spk_288
    - spk_289
    - spk_29
    - spk_290
    - spk_291
    - spk_292
    - spk_293
    - spk_294
    - spk_295
    - spk_296
    - spk_297
    - spk_298
    - spk_299
    - spk_3
    - spk_30
    - spk_300
    - spk_301
    - spk_302
    - spk_303
    - spk_304
    - spk_305
    - spk_306
    - spk_307
    - spk_308
    - spk_309
    - spk_31
    - spk_310
    - spk_311
    - spk_312
    - spk_313
    - spk_314
    - spk_315
    - spk_316
    - spk_317
    - spk_318
    - spk_319
    - spk_32
    - spk_320
    - spk_321
    - spk_322
    - spk_323
    - spk_324
    - spk_325
    - spk_326
    - spk_327
    - spk_328
    - spk_329
    - spk_33
    - spk_330
    - spk_331
    - spk_332
    - spk_333
    - spk_334
    - spk_335
    - spk_336
    - spk_337
    - spk_338
    - spk_339
    - spk_34
    - spk_340
    - spk_341
    - spk_342
    - spk_343
    - spk_344
    - spk_345
    - spk_346
    - spk_347
    - spk_348
    - spk_349
    - spk_35
    - spk_350
    - spk_351
    - spk_352
    - spk_353
    - spk_354
    - spk_355
    - spk_356
    - spk_357
    - spk_358
    - spk_359
    - spk_36
    - spk_360
    - spk_361
    - spk_362
    - spk_363
    - spk_364
    - spk_365
    - spk_366
    - spk_367
    - spk_368
    - spk_369
    - spk_37
    - spk_370
    - spk_371
    - spk_372
    - spk_373
    - spk_374
    - spk_375
    - spk_376
    - spk_377
    - spk_378
    - spk_379
    - spk_38
    - spk_380
    - spk_381
    - spk_382
    - spk_383
    - spk_384
    - spk_385
    - spk_386
    - spk_387
    - spk_388
    - spk_389
    - spk_39
    - spk_390
    - spk_391
    - spk_392
    - spk_393
    - spk_394
    - spk_395
    - spk_396
    - spk_397
    - spk_398
    - spk_399
    - spk_4
    - spk_40
    - spk_400
    - spk_401
    - spk_402
    - spk_403
    - spk_404
    - spk_405
    - spk_406
    - spk_407
    - spk_408
    - spk_409
    - spk_41
    - spk_410
    - spk_411
    - spk_412
    - spk_413
    - spk_414
    - spk_415
    - spk_416
    - spk_417
    - spk_418
    - spk_419
    - spk_42
    - spk_420
    - spk_421
    - spk_422
    - spk_423
    - spk_424
    - spk_425
    - spk_426
    - spk_427
    - spk_428
    - spk_429
    - spk_43
    - spk_430
    - spk_431
    - spk_432
    - spk_433
    - spk_434
    - spk_435
    - spk_436
    - spk_437
    - spk_438
    - spk_439
    - spk_44
    - spk_440
    - spk_441
    - spk_442
    - spk_443
    - spk_444
    - spk_445
    - spk_446
    - spk_447
    - spk_448
    - spk_449
    - spk_45
    - spk_450
    - spk_451
    - spk_452
    - spk_453
    - spk_454
    - spk_455
    - spk_456
    - spk_457
    - spk_458
    - spk_459
    - spk_46
    - spk_460
    - spk_461
    - spk_462
    - spk_463
    - spk_464
    - spk_465
    - spk_466
    - spk_467
    - spk_468
    - spk_469
    - spk_47
    - spk_470
    - spk_471
    - spk_472
    - spk_473
    - spk_474
    - spk_475
    - spk_476
    - spk_477
    - spk_478
    - spk_479
    - spk_48
    - spk_480
    - spk_481
    - spk_482
    - spk_483
    - spk_484
    - spk_485
    - spk_486
    - spk_487
    - spk_488
    - spk_489
    - spk_49
    - spk_490
    - spk_491
    - spk_492
    - spk_493
    - spk_494
    - spk_495
    - spk_496
    - spk_497
    - spk_498
    - spk_499
    - spk_5
    - spk_50
    - spk_500
    - spk_501
    - spk_502
    - spk_503
    - spk_504
    - spk_505
    - spk_506
    - spk_507
    - spk_508
    - spk_509
    - spk_51
    - spk_510
    - spk_511
    - spk_512
    - spk_513
    - spk_514
    - spk_515
    - spk_516
    - spk_517
    - spk_518
    - spk_519
    - spk_52
    - spk_520
    - spk_521
    - spk_522
    - spk_523
    - spk_524
    - spk_525
    - spk_526
    - spk_527
    - spk_528
    - spk_529
    - spk_53
    - spk_530
    - spk_531
    - spk_532
    - spk_533
    - spk_534
    - spk_535
    - spk_536
    - spk_537
    - spk_538
    - spk_539
    - spk_54
    - spk_540
    - spk_541
    - spk_542
    - spk_543
    - spk_544
    - spk_545
    - spk_546
    - spk_547
    - spk_548
    - spk_549
    - spk_55
    - spk_550
    - spk_551
    - spk_552
    - spk_553
    - spk_554
    - spk_555
    - spk_556
    - spk_557
    - spk_558
    - spk_559
    - spk_56
    - spk_560
    - spk_561
    - spk_562
    - spk_563
    - spk_564
    - spk_565
    - spk_566
    - spk_567
    - spk_568
    - spk_569
    - spk_57
    - spk_570
    - spk_571
    - spk_572
    - spk_573
    - spk_574
    - spk_575
    - spk_576
    - spk_577
    - spk_578
    - spk_579
    - spk_58
    - spk_580
    - spk_581
    - spk_582
    - spk_583
    - spk_584
    - spk_585
    - spk_586
    - spk_587
    - spk_588
    - spk_589
    - spk_59
    - spk_590
    - spk_591
    - spk_592
    - spk_593
    - spk_594
    - spk_595
    - spk_596
    - spk_597
    - spk_598
    - spk_599
    - spk_6
    - spk_60
    - spk_600
    - spk_601
    - spk_602
    - spk_603
    - spk_604
    - spk_605
    - spk_606
    - spk_607
    - spk_608
    - spk_609
    - spk_61
    - spk_610
    - spk_611
    - spk_612
    - spk_613
    - spk_614
    - spk_615
    - spk_616
    - spk_617
    - spk_618
    - spk_619
    - spk_62
    - spk_620
    - spk_621
    - spk_622
    - spk_623
    - spk_624
    - spk_625
    - spk_626
    - spk_627
    - spk_628
    - spk_629
    - spk_63
    - spk_630
    - spk_631
    - spk_632
    - spk_633
    - spk_634
    - spk_635
    - spk_636
    - spk_637
    - spk_638
    - spk_639
    - spk_64
    - spk_640
    - spk_641
    - spk_642
    - spk_643
    - spk_644
    - spk_645
    - spk_646
    - spk_647
    - spk_648
    - spk_649
    - spk_65
    - spk_650
    - spk_66
    - spk_67
    - spk_68
    - spk_69
    - spk_7
    - spk_70
    - spk_71
    - spk_72
    - spk_73
    - spk_74
    - spk_75
    - spk_76
    - spk_77
    - spk_78
    - spk_79
    - spk_8
    - spk_80
    - spk_81
    - spk_82
    - spk_83
    - spk_84
    - spk_85
    - spk_86
    - spk_87
    - spk_88
    - spk_89
    - spk_9
    - spk_90
    - spk_91
    - spk_92
    - spk_93
    - spk_94
    - spk_95
    - spk_96
    - spk_97
    - spk_98
    - spk_99
    batch_size: 64
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: null
    tarred_shard_strategy: scatter
    augmentor: null
  validation_ds:
    manifest_filepath: datas/valid.json
    sample_rate: 16000
    labels: null
    batch_size: 128
    shuffle: false
  model_defaults:
    filters: 1024
    repeat: 3
    dropout: 0.1
    separable: true
    se: true
    se_context_size: -1
    kernel_size_factor: 1.0
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: per_feature
    window_size: 0.025
    sample_rate: 16000
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 3
    freq_width: 4
    time_masks: 5
    time_width: 0.03
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 80
    activation: relu
    conv_mask: true
    jasper:
    - filters: 1024
      repeat: 1
      kernel:
      - 3
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 1024
      repeat: 3
      kernel:
      - 7
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.1
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 1024
      repeat: 3
      kernel:
      - 11
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.1
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 1024
      repeat: 3
      kernel:
      - 15
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.1
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 3072
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
  decoder:
    _target_: nemo.collections.asr.modules.SpeakerDecoder
    feat_in: 3072
    num_classes: 652
    pool_mode: attention
    emb_sizes: 192
  loss:
    _target_: nemo.collections.asr.losses.angularloss.AngularSoftmaxLoss
    scale: 30
    margin: 0.2
  optim:
    name: sgd
    lr: 0.006
    weight_decay: 0.0002
    momentum: 0.9
    sched:
      name: CosineAnnealing
      warmup_ratio: 0.1
      min_lr: 0.0
  target: nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel
  nemo_version: 1.18.0rc0